### PR TITLE
Deps

### PR DESCRIPTION
**Pull request by shrunyan**
Update starter to use extracted package. [https://github.com/zesty-io/nextjs-sync](https://github.com/zesty-io/nextjs-sync)

The starter will only be aware of the nextjs-sync package. The nextjs-sync package depends on a few others which have been either extracted or improved. This complete stack of dependencies is required for that starter to operate.

- https://github.com/zesty-io/webengine-json
- https://github.com/zesty-io/cli/pull/123
- https://github.com/zesty-io/cli/pull/124

These changes introduce a signficant change in how environment variables are handled. Moving from a custom `zesty.config.js` file to the standard nextjs `.env` file.

It also abandons a few unnecessary variables. 

- `src_dir` is not necessary as nextjs only allows root or `src`. So instead opt to behave similarly to nextjs and determine which one the user has decided on by inspecting the file system

Additionally a few values are now derived and require no user action to setup.
 
- preview url: {HASH}-dev.webengine.zesty.io 
- production url
- instance zuid

Other variables have been moved from the prior `zesty.config.js` file into the cli managed `.zesty/config.js` file. Consolidating where zesty configurations occur. 

- preview password

### CODE REVIEW

**Review by agalin920 — COMMENTED** [review]
@shrunyan How are we determining whether to hit stage url or prod url? Or are we defaulting to to one?

**Comment by shrunyan** [comment]
> @shrunyan How are we determining whether to hit stage url or prod url? Or are we defaulting to to one?

The domain selection is a nextjs specific detail and so it is contained within the nextjs-sync lib. https://github.com/zesty-io/nextjs-sync/blob/main/src/fetchPageJson.js#L20

**Comment by agalin920** [comment]
@shrunyan Sweet. Thanks

**Comment by shrunyan** [comment]
To solve for a user being able to run sync without being logged in or the presence of the `.zesty` folder I plan to change the logic to start with the `.env` file. Which is honestly all it needs. The `.zesty` folder is a mechanism for the cli and not actually necessary for the starter. So we can ignore that directory in the `.gitignore` file.

For model ignore I'll add another env var. `ZESTY_MODEL_IGNORE_LIST=6-000-0000,6-000-0000,6-000-0000...`

The logic changes will be made in https://github.com/zesty-io/nextjs-sync

**Review by ardeay — APPROVED** [review]

**Comment by ardeay** [comment]
@shrunyan @agalin920 i merged this to get the latest README in, @shrunyan I'd still like to see changes to zesty config setup

**Pull request merged**
